[project]
name = "wild-eval"
version = "0.1.0"
description = "WildEval - Experimental AI evaluation framework for biodiversity data tasks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "spacy>=3.7.0",
    "autoevals",
    "requests>=2.25.0",
    "openai>=1.0.0",
]
